// Generated by jextract

package org.openjdk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$4 {

    static final FunctionDescriptor JImageResourceIterator_t$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle JImageResourceIterator_t$MH = RuntimeHelper.downcallHandle(
        constants$4.JImageResourceIterator_t$FUNC, false
    );
    static final MemorySegment __DARWIN_SUF_64_BIT_INO_T$SEGMENT = ResourceScope.globalScope().allocateUtf8String("$INODE64");
    static final MemorySegment __DARWIN_SUF_1050$SEGMENT = ResourceScope.globalScope().allocateUtf8String("$1050");
    static final MemorySegment __DARWIN_SUF_EXTSN$SEGMENT = ResourceScope.globalScope().allocateUtf8String("$DARWIN_EXTSN");
    static final MemoryAddress RTLD_NEXT$ADDR = MemoryAddress.ofLong(-1L);
}


