// Generated by jextract

package org.openjdk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$5 {

    static final MemoryAddress RTLD_DEFAULT$ADDR = MemoryAddress.ofLong(-2L);
    static final MemoryAddress RTLD_SELF$ADDR = MemoryAddress.ofLong(-3L);
    static final MemoryAddress RTLD_MAIN_ONLY$ADDR = MemoryAddress.ofLong(-5L);
}


